CREATE TABLE IF NOT EXISTS `jogo` (
  `adversario` varchar(50) NOT NULL,
  `golsBotafogo` int(2) NOT NULL,
  `golsAdversario` int(2) NOT NULL,
  `campeonato` enum('Carioca','Série A','Série B','Libertadores','Copa do Brasil','Sul-Americana','Amistoso','Mundial') NOT NULL,
  `dataJogo` date NOT NULL,
  `estadio` varchar(50) NOT NULL,
  `tecnico` varchar(50) NOT NULL,
  `autorBotafogo` text NOT NULL,
  `autorAdversario` text NOT NULL,
  PRIMARY KEY (`dataJogo`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `jogo`
--

INSERT INTO `jogo` (`adversario`, `golsBotafogo`, `golsAdversario`, `campeonato`, `dataJogo`, `estadio`, `tecnico`, `autorBotafogo`, `autorAdversario`) VALUES
('Fluminense', 2, 3, 'Série A', '2002-10-26', 'Maracanã', 'Ivo Wortmann', '-Galeano <br />-Léo Inácio', '-César <br />-Magno Alves <br />-Romário'),
('Flamengo', 1, 0, 'Carioca', '2004-03-14', 'Maracanã', 'Levir Culpi', '-Alex Alves', ''),
('Atlético-PR', 1, 1, 'Série A', '2004-08-12', 'Caio Martins', 'Mauro Galvão', '-Schwenck', '-Washington'),
('Criciúma', 1, 1, 'Série A', '2004-08-28', 'Caio Martins', 'Paulo Bonamigo', '-Schwenck', '-Fernandinho'),
('Fluminense', 4, 1, 'Série A', '2004-10-02', 'Maracanã', 'Paulo Bonamigo', '-Almir <br />-Ruy <br />-Ricardinho <br />-Têti', '-Edmundo'),
('Coritiba', 4, 1, 'Série A', '2004-11-13', 'Caio Martins', 'Paulo Bonamigo', '-Caio Ribeiro (2x)  <br />-Schwenck <br />-Ricardinho', '-Jorginho Paulista'),
('Guarani', 1, 0, 'Série A', '2004-11-27', 'Caio Martins', 'Paulo Bonamigo', '-Alex Alves', ''),
('Corinthians', 1, 2, 'Série A', '2004-12-12', 'Caio Martins', 'Paulo Bonamigo', '-Alex Alves', '-Fábio Baiano <br />-Wendel'),
('Americano', 1, 2, 'Carioca', '2005-02-13', 'Maracanã', 'Paulo Bonamigo', '-Alex Alves', '-Marcos Antônio <br />-Washington'),
('Fluminense', 0, 4, 'Carioca', '2005-03-13', 'Maracanã', 'Paulo Bonamigo', '', '-Fabiano Eller <br />-Gabriel <br />-Juninho <br />-Alex'),
('Atlético-PR', 2, 0, 'Série A', '2005-05-29', 'Luso Brasileiro', 'Paulo César Gusmão', '-Rafael Marques <br />-Almir', ''),
('Goiás', 3, 1, 'Série A', '2005-09-18', 'Luso Brasileiro', 'Celso Roth', '-Ramón <br />-Zé Roberto (2x)', '-Souza'),
('Palmeiras', 1, 2, 'Série A', '2005-10-08', 'Luso Brasileiro', 'Celso Roth', '-Alex Alves', '-Marcinho Guerreiro <br />-Marcinho'),
('Paraná', 2, 0, 'Série A', '2005-11-12', 'Luso Brasileiro', 'Celso Roth', '-Ramón <br/>-Juca', ''),
('Vasco', 5, 3, 'Carioca', '2006-01-22', 'Maracanã', 'Carlos Roberto', '-Zé Roberto<br/>-Lúcio Flávio<br/>-Reinaldo<br/>-Ruy<br/>-Felipe Adão', '-Romário (3x)'),
('Nova Iguaçu', 1, 1, 'Carioca', '2006-02-19', 'Maracanã', 'Carlos Roberto', '-Dodô', '-Marcos Denner'),
('Madureira', 3, 1, 'Carioca', '2006-04-09', 'Maracanã', 'Carlos Roberto', '-Dodô (2x)<br/>-Reinaldo', '-Fábio Júnior'),
('Grêmio', 2, 2, 'Série A', '2006-05-13', 'Maracanã', 'Carlos Roberto', '-Reinaldo<br/>-Christian', '-Ricardinho<br/>-Alessandro'),
('Santos', 4, 3, 'Série A', '2006-10-14', 'Maracanã', 'Cuca', '-Asprilla<br/>-Reinaldo<br/>-Zé Roberto<br/>-Juca', '-Kléber<br/>-Welligton Paulista<br/>-Reinaldo'),
('São Caetano', 2, 1, 'Série A', '2006-10-22', 'Maracanã', 'Cuca', '-Juninho<br/>-Reinaldo', '-Marabá'),
('Internacional', 0, 1, 'Série A', '2006-11-02', 'Maracanã', 'Cuca', '', '-Alex Meschini'),
('Goiás', 2, 2, 'Série A', '2006-11-19', 'Maracanã', 'Cuca', '-Wando<br/>-Lúcio Flávio', '-Robson Luiz<br/>-Rogério Corrêa'),
('Figueirense', 3, 1, 'Copa do Brasil', '2007-05-23', 'Maracanã', 'Cuca', '-Zé Roberto<br/>-André Lima<br/>-Vinícius (Gol Contra)', '-Cleiton Xavier'),
('Grêmio', 3, 0, 'Série A', '2007-06-02', 'Maracanã', 'Cuca', '-Juninho<br/>-Luciano Almeida<br/>-Dodô', ''),
('Náutico', 3, 1, 'Série A', '2007-06-17', 'Maracanã', 'Cuca', '-Juninho<br/>-André Lima<br/>-Jorge Henrique', '-Alex (Gol Contra)'),
('Internacional', 1, 1, 'Série A', '2007-08-19', 'Maracanã', 'Cuca', '-André Lima', '-Ceará'),
('Fluminense', 0, 2, 'Série A', '2007-09-23', 'Maracanã', 'Cuca', '', '-Thiago Neves<br/>-David'),
('Fluminense', 3, 1, 'Carioca', '2008-03-30', 'Maracanã', 'Cuca', '-Welligton Paulista<br/>-Lúcio Flávio<br/>-Jorge Henrique', '-Alan'),
('Atlético-MG', 2, 0, 'Copa do Brasil', '2008-05-14', 'Nilton Santos', 'Cuca', '-Zé Carlos<br/>-Alessandro', ''),
('Vasco', 1, 1, 'Série A', '2008-05-25', 'Nilton Santos', 'Cuca', '-Lúcio Flávio', '-Eduardo Luiz'),
('Náutico', 1, 1, 'Série A', '2008-08-30', 'Nilton Santos', 'Ney Franco', '-Carlos Alberto', '-Adriano'),
('Fluminense', 1, 2, 'Carioca', '2009-03-28', 'Maracanã', 'Ney Franco', '-Maicosuel', '-Maicon<br/>-Conca'),
('Boavista', 4, 1, 'Carioca', '2010-03-29', 'São Januário', 'Joel Santana', '-Loco Abreu (3x)<br/>-Marcelo Cordeiro', '-Tony'),
('Atlético-MG', 3, 0, 'Série A', '2010-08-07', 'Nilton Santos', 'Joel Santana', '-Maicosuel<br/>-Somália<br/>-Herrera', ''),
('Vitória', 1, 0, 'Série A', '2010-10-23', 'Nilton Santos', 'Joel Santana', '-Marcelo Cordeiro', ''),
('Volta Redonda', 4, 2, 'Carioca', '2011-03-05', 'Nilton Santos', 'Joel Santana', '-Caio<br/>-Herrera<br/>-Alex<br/>-Rodrigo Mancha', '-Gláuber<br/>-Cristiano Ávalos'),
('Vasco', 0, 2, 'Carioca', '2011-03-20', 'Nilton Santos', 'Joel Santana', '', '-Éder Luís<br/>-Diego Souza'),
('Ceará', 4, 0, 'Série A', '2011-09-07', 'Nilton Santos', 'Caio Júnior', '-Herrera (2x)<br/>-Loco Abreu<br/>-Cidinho', ''),
('Bahia', 2, 2, 'Série A', '2011-10-08', 'São Januário', 'Caio Júnior', '-Alex<br/>-Caio', '-Souza (2x)'),
('Vasco', 3, 1, 'Carioca', '2012-04-29', 'Nilton Santos', 'Oswaldo de Oliveira', '-Loco Abreu (2x)<br/>-Maicosuel', '-Carlos Alberto'),
('Flamengo', 0, 1, 'Carioca', '2013-02-17', 'Nilton Santos', 'Oswaldo de Oliveira', '', '-Hernane'),
('Fluminense', 1, 0, 'Carioca', '2013-05-05', 'Raulino de Oliveira (Volta Redonda)', 'Oswaldo de Oliveira', '-Rafael Marques', ''),
('Grêmio', 0, 1, 'Série A', '2013-10-05', 'Maracanã', 'Oswaldo de Oliveira', '', '-Alex Telles'),
('Criciúma', 3, 0, 'Série A', '2013-12-08', 'Maracanã', 'Oswaldo de Oliveira', '-Lodeiro<br/>-Elias<br/>-Seedorf', ''),
('Deportivo Quito', 4, 0, 'Libertadores', '2014-02-05', 'Maracanã', 'Eduardo Húngaro', '-Wallyson (3x)<br/>-Henrique Almeida', ''),
('Independiente Del Valle', 1, 0, 'Libertadores', '2014-03-18', 'Maracanã', 'Eduardo Húngaro', '-\'El Tanque\' Ferreyra', ''),
('Flamengo', 0, 1, 'Série A', '2014-07-27', 'Maracanã', 'Vagner Mancini', '', '-Alecsandro'),
('Chapecoense', 1, 0, 'Série A', '2014-08-23', 'Maracanã', 'Vagner Mancini', '-Cachito Ramírez', ''),
('Santos', 1, 0, 'Série A', '2014-08-31', 'Maracanã', 'Vagner Mancini', '-Daniel', ''),
('Bahia', 2, 3, 'Série A', '2014-09-17', 'Maracanã', 'Vagner Mancini', '-Emerson Sheik (2x)', '-Dankler (Gol Contra)<br/>-Maxi Biancucchi<br/>-Branquinho'),
('Palmeiras', 0, 1, 'Série A', '2014-10-08', 'Maracanã', 'Vagner Mancini', '', '-Henrique Dourado'),
('Boavista', 1, 0, 'Carioca', '2015-01-31', 'São Januário', 'Renê Simões', '-Roger Carvalho', ''),
('Bonsucesso', 4, 0, 'Carioca', '2015-02-07', 'Nilton Santos', 'Renê Simões', '-Diego Jardel<br/>-Bill<br/>-Thiago Carleto<br/>-Fernandes', ''),
('Nova Iguaçu', 2, 1, 'Carioca', '2015-02-21', 'Nilton Santos', 'Renê Simões', '-Paulo Henrique (Gol Contra)<br/>-Jóbson', '-Marlon'),
('Flamengo', 1, 0, 'Carioca', '2015-03-01', 'Maracanã', 'Renê Simões', '-Tomás Bastos', ''),
('Fluminense', 1, 3, 'Carioca', '2015-03-08', 'Maracanã', 'Renê Simões', '-Jóbson', '-Kenedy<br/>-Gerson<br/>-Fred'),
('Resende', 3, 0, 'Carioca', '2015-03-15', 'Nilton Santos', 'Renê Simões', '-Tássio<br/>-Jóbson<br/>-Rodrigo Pimpão', ''),
('Vasco', 1, 1, 'Carioca', '2015-03-29', 'Maracanã', 'Renê Simões', '-Roger Carvalho', '-Gilberto'),
('Madureira', 4, 1, 'Carioca', '2015-04-05', 'Nilton Santos', 'Renê Simões', '-Thiago Carleto<br/>-Renan Fonseca<br/>-Fernandes<br/>-Bill', '-Rodrigo Lindoso'),
('Vasco', 1, 2, 'Carioca', '2015-05-03', 'Maracanã', 'Renê Simões', '-Diego Jardel', '-Rafael Silva<br/>-Gilberto'),
('CRB', 4, 1, 'Série B', '2015-05-16', 'Nilton Santos', 'Renê Simões', '-Bill<br/>-Lulinha<br/>-William Arão<br/>-Élvis', '-Fernando'),
('Vitória', 2, 0, 'Série B', '2015-05-30', 'Nilton Santos', 'Renê Simões', '-Diego Giaretta<br/>-William Arão', ''),
('Mogi Mirim', 3, 0, 'Série B', '2015-06-05', 'Nilton Santos', 'Renê Simões', '-Rodrigo Pimpão<br/>-Bill<br/>-Lulinha', ''),
('Boa Esporte', 1, 1, 'Série B', '2015-06-19', 'Nilton Santos', 'Renê Simões', '-Rodrigo Pimpão', '-Bruninho'),
('Figueirense', 0, 1, 'Copa do Brasil', '2015-07-14', 'Nilton Santos', 'Renê Simões', '', '-Marcão'),
('Criciúma', 0, 0, 'Série B', '2015-07-28', 'Nilton Santos', 'Ricardo Gomes', '', ''),
('Paysandu', 2, 3, 'Série B', '2015-08-23', 'Nilton Santos', 'Ricardo Gomes', '-Daniel Carvalho<br/>-Sassá', '-Yago Pikachu<br/>-Thiago Martins<br/>-Jhonnatan'),
('Bragantino', 4, 0, 'Série B', '2015-10-17', 'Nilton Santos', 'Ricardo Gomes', '-Navarro (2x)<br/>-William Arão<br/>-Neílton', ''),
('Santa Cruz', 0, 3, 'Série B', '2015-11-14', 'Nilton Santos', 'Ricardo Gomes', '', '-Lelê<br/>-Grafite<br/>-Bruno Moraes'),
('América-MG', 0, 0, 'Série B', '2015-11-28', 'Nilton Santos', 'Ricardo Gomes', '', ''),
('Portuguesa-RJ', 2, 1, 'Carioca', '2016-02-02', 'São Januário', 'Ricardo Gomes', '-Gegê<br/>-Damián Lizio', '-Rafael Paty'),
('Boavista', 1, 0, 'Carioca', '2016-03-06', 'São Januário', 'Ricardo Gomes', '-Fernandes', ''),
('Vasco', 0, 1, 'Carioca', '2016-05-01', 'Maracanã', 'Ricardo Gomes', '', '-Jorge Henrique'),
('Vasco', 1, 1, 'Carioca', '2016-05-08', 'Maracanã', 'Ricardo Gomes', '-Leandrinho', '-Rafael Vaz'),
('São Paulo', 0, 1, 'Série A', '2016-05-15', 'Raulino de Oliveira (Volta Redonda)', 'Ricardo Gomes', '', '-Lucas Fernandes'),
('Santa Cruz', 2, 1, 'Série A', '2016-07-03', 'Mário Helênio (Juiz de Fora)', 'Ricardo Gomes', '-Sassá<br/>-Neílton', '-João Paulo'),
('Palmeiras', 3, 1, 'Série A', '2016-07-31', 'Arena Botafogo', 'Jair Ventura', '-Neílton (2x)<br/>-Camilo', '-Erik'),
('Grêmio', 2, 1, 'Série A', '2016-09-04', 'Arena Botafogo', 'Jair Ventura', '-Camilo<br/>-Sassá', '-Batista'),
('Fluminense', 1, 0, 'Série A', '2016-09-07', 'Arena Botafogo', 'Jair Ventura', '-Neílton', ''),
('Internacional', 1, 0, 'Série A', '2016-10-12', 'Arena Botafogo', 'Jair Ventura', '-Sassá', ''),
('Atlético-MG', 3, 2, 'Série A', '2016-10-16', 'Arena Botafogo', 'Jair Ventura', '-Bruno Silva<br/>-Rodrigo Pimpão<br/>-Dudu Cearense', '-Fred<br/>-Leonardo Silva'),
('Coritiba', 0, 0, 'Série A', '2016-10-29', 'Arena Botafogo', 'Jair Ventura', '', ''),
('Chapecoense', 0, 2, 'Série A', '2016-11-16', 'Arena Botafogo', 'Jair Ventura', '', '-Kempes<br/>-Sérgio Manoel'),
('Ponte Preta', 1, 1, 'Série A', '2016-11-26', 'Arena Botafogo', 'Jair Ventura', '-Sassá', '-William Potker'),
('Nova Iguaçu', 1, 1, 'Carioca', '2017-01-28', 'Nilton Santos', 'Jair Ventura', '-Marcelo Benevenuto', '-Murilo Henrique'),
('Colo-Colo', 2, 1, 'Libertadores', '2017-02-01', 'Nilton Santos', 'Jair Ventura', '-Airton<br/>-Esteban Pavez (Gol Contra)', '-Paredes'),
('Macaé', 2, 1, 'Carioca', '2017-02-04', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Lindoso<br/>-Vinicius Tanque', '-Guilherme Xavier'),
('Olimpia', 1, 0, 'Libertadores', '2017-02-15', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Pimpão', ''),
('Volta Redonda', 1, 0, 'Carioca', '2017-03-09', 'Nilton Santos', 'Jair Ventura', '-Victor Luís', ''),
('Vasco', 0, 0, 'Carioca', '2017-03-19', 'Nilton Santos', 'Jair Ventura', '', ''),
('Fluminense', 2, 3, 'Carioca', '2017-03-23', 'Nilton Santos', 'Jair Ventura', '-Roger (2x)', '-Richarlison (2x)<br/>-Renato Chaves'),
('Fluminense', 3, 1, 'Carioca', '2017-04-09', 'Nilton Santos', 'Jair Ventura', '-Igor Rabello<br/>-Dudu Cearense<br/>-Sassá', '-Richarlison'),
('Vasco', 0, 2, 'Carioca', '2017-04-16', 'Nilton Santos', 'Jair Ventura', '', '-Douglas Luiz<br/>-Luís Fabiano'),
('Sport', 2, 1, 'Copa do Brasil', '2017-04-26', 'Nilton Santos', 'Jair Ventura', '-Guilherme (2x)', '-Samuel Xavier'),
('Barcelona SC', 0, 2, 'Libertadores', '2017-05-02', 'Nilton Santos', 'Jair Ventura', '', '-Ayoví<br/>-Jonatan Álvez'),
('Atlético Nacional', 1, 0, 'Libertadores', '2017-05-18', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Pimpão', ''),
('Ponte Preta', 2, 0, 'Série A', '2017-05-21', 'Nilton Santos', 'Jair Ventura', '-Bruno Silva <br />-Rodrigo Lindoso', ''),
('Bahia', 1, 0, 'Série A', '2017-05-28', 'Nilton Santos', 'Jair Ventura', '-Bruno Silva', ''),
('Coritiba', 2, 2, 'Série A', '2017-06-11', 'Nilton Santos', 'Jair Ventura', '-Roger<br/>-Joel Carli', '-Kléber<br/>-Henrique Almeida'),
('Vasco', 3, 1, 'Série A', '2017-06-21', 'Nilton Santos', 'Jair Ventura', '-Roger (2x)<br/>-Victor Luís', '-Caio Monteiro'),
('Avaí', 0, 2, 'Série A', '2017-06-26', 'Nilton Santos', 'Jair Ventura', '', '-Joel (2x)'),
('Atlético-MG', 1, 1, 'Série A', '2017-07-09', 'Nilton Santos', 'Jair Ventura', '-Roger', '-Marlone'),
('Fluminense', 1, 0, 'Série A', '2017-07-12', 'Maracanã', 'Jair Ventura', '-Roger', ''),
('Sport', 2, 1, 'Série A', '2017-07-17', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Lindoso<br/>-Guilherme', '-Rithely'),
('Atlético-MG', 3, 0, 'Copa do Brasil', '2017-07-26', 'Nilton Santos', 'Jair Ventura', '-Joel Carli<br/>-Roger<br/>-Gilson', ''),
('São Paulo', 3, 4, 'Série A', '2017-07-29', 'Nilton Santos', 'Jair Ventura', '-Marcos Vinícius (2x) <br/>-Guilherme', '-Cueva <br/>-Marcos Guilherme (2x)<br/>-Hernanes'),
('Palmeiras', 1, 2, 'Série A', '2017-08-02', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Pimpão', '-Igor Rabello (Gol Contra) <br/>-Deyverson'),
('Nacional-URU', 2, 0, 'Libertadores', '2017-08-10', 'Nilton Santos', 'Jair Ventura', '-Bruno Silva <br/>-Rodrigo Pimpão', ''),
('Grêmio', 1, 0, 'Série A', '2017-08-13', 'Nilton Santos', 'Jair Ventura', '-Leandrinho', ''),
('Flamengo', 0, 0, 'Copa do Brasil', '2017-08-16', 'Nilton Santos', 'Jair Ventura', '', ''),
('Flamengo', 0, 1, 'Copa do Brasil', '2017-08-23', 'Nilton Santos', 'Jair Ventura', '', '-Diego'),
('Flamengo', 2, 0, 'Série A', '2017-09-10', 'Nilton Santos', 'Jair Ventura', '-Roger (2x)', ''),
('Grêmio', 0, 0, 'Libertadores', '2017-09-13', 'Nilton Santos', 'Jair Ventura', '', ''),
('Santos', 2, 0, 'Série A', '2017-09-16', 'Nilton Santos', 'Jair Ventura', '-Rodrigo Lindoso <br/>-Guilherme', ''),
('Vitória', 2, 3, 'Série A', '2017-10-01', 'Nilton Santos', 'Jair Ventura', '-Brenner (2x)', '-David <br/>-André Lima <br/>-Danilinho'),
('Chapecoense', 2, 1, 'Série A', '2017-10-11', 'Nilton Santos', 'Jair Ventura', '-Brenner <br/>-Vinicius Tanque', '-Apodi'),
('Vasco', 0, 1, 'Série A', '2017-10-14', 'Maracanã', 'Jair Ventura', '', '-Nenê'),
('Corinthians', 2, 1, 'Série A', '2017-10-23', 'Nilton Santos', 'Jair Ventura', '-Brenner <br/>-Igor Rabello', '-Jô'),
('Fluminense', 1, 2, 'Série A', '2017-11-04', 'Nilton Santos', 'Jair Ventura', '-Marcos Vinícius', '-Marcos Júnior <br/>-Matheus Alessandro'),
('Atlético-PR', 0, 1, 'Série A', '2017-11-11', 'Nilton Santos', 'Jair Ventura', '', '-Guilherme'),
('Atlético-GO', 1, 2, 'Série A', '2017-11-16', 'Nilton Santos', 'Jair Ventura', '-João Paulo', '-Jorginho <br/>-Luiz Fernando'),
('Cruzeiro', 2, 2, 'Série A', '2017-12-03', 'Nilton Santos', 'Jair Ventura', '-Brenner <br/>-Ezequiel', '-Thiago Neves <br/>-Arrascaeta'),
('Portuguesa-RJ', 2, 2, 'Carioca', '2018-01-16', 'Nilton Santos', 'Felipe Conceição (Tigrão)', '-Brenner <br/>-Marcos Vinícius', '-Jefferson Oliveira (2x)'),
('Fluminense', 0, 0, 'Carioca', '2018-01-20', 'Maracanã', 'Felipe Conceição (Tigrão)', '', ''),
('Boavista', 1, 0, 'Carioca', '2018-01-28', 'Nilton Santos', 'Felipe Conceição (Tigrão)', '-Brenner', ''),
('Madureira', 0, 0, 'Carioca', '2018-02-03', 'Nilton Santos', 'Felipe Conceição (Tigrão)', '', ''),
('Bangu', 1, 0, 'Carioca', '2018-03-06', 'Nilton Santos', 'Alberto Valentim', '-Rodrigo Pimpão', ''),
('Vasco', 2, 3, 'Carioca', '2018-03-18', 'Nilton Santos', 'Alberto Valentim', '-Rodrigo Lindoso <br/>-Brenner', '-Riascos <br/>-Andrés Ríos <br/>-Paulinho'),
('Vasco', 3, 2, 'Carioca', '2018-03-21', 'Nilton Santos', 'Alberto Valentim', '-Brenner <br/>-Luiz Fernando <br/>-Igor Rabello', '-Erazo <br/>-Riascos'),
('Fluminense', 0, 3, 'Carioca', '2018-03-25', 'Maracanã', 'Alberto Valentim', '', '-Pedro <br/>-Marcos Júnior <br/>-Jadson'),
('Flamengo', 1, 0, 'Carioca', '2018-03-28', 'Maracanã', 'Alberto Valentim', '-Luiz Fernando', ''),
('Vasco', 2, 3, 'Carioca', '2018-04-01', 'Nilton Santos', 'Alberto Valentim', '-Renatinho <br/>-Brenner', '-Yago Pikachu (2x) <br/>-Andrés Ríos'),
('Vasco', 1, 0, 'Carioca', '2018-04-08', 'Maracanã', 'Alberto Valentim', '-Joel Carli', ''),
('Grêmio', 2, 1, 'Série A', '2018-04-28', 'Nilton Santos', 'Alberto Valentim', '-Brenner <br/>-Gilson', '-Igor Rabello (Gol Contra)'),
('Audax Italiano', 1, 1, 'Sul-Americana', '2018-05-09', 'Nilton Santos', 'Alberto Valentim', '-Matheus Fernandes', '-Luis Cabrera'),
('Fluminense', 2, 1, 'Série A', '2018-05-14', 'Nilton Santos', 'Alberto Valentim', '-Rodrigo Lindoso <br/>-Kieza', '-Pedro'),
('Vitória', 1, 1, 'Série A', '2018-05-27', 'Nilton Santos', 'Alberto Valentim', '-Kieza', '-Denílson'),
('Vasco', 2, 1, 'Série A', '2018-06-02', 'São Januário', 'Alberto Valentim', '-Kieza <br/>-Igor Rabello', '-Andrey'),
('Ceará', 0, 0, 'Série A', '2018-06-06', 'Nilton Santos', 'Alberto Valentim', '', ''),
('Chapecoense', 1, 0, 'Série A', '2018-07-26', 'Nilton Santos', 'Marcos Paquetá', '-Marcinho', ''),
('Santos', 0, 0, 'Série A', '2018-08-04', 'Nilton Santos', 'Bruno Lazaroni', '', ''),
('Nacional-PAR', 2, 0, 'Sul-Americana', '2018-08-16', 'Nilton Santos', 'Zé Ricardo', '-Rodrigo Lindoso <br/>-Léo Valencia', ''),
('Atlético-MG', 0, 3, 'Série A', '2018-08-19', 'Nilton Santos', 'Zé Ricardo', '', '-Luan <br/>-Cazares <br/>-Tomás Andrade'),
('Sport', 2, 0, 'Série A', '2018-08-25', 'Nilton Santos', 'Zé Ricardo', '-Joel Carli <br/>-Rodrigo Aguirre', ''),
('Cruzeiro', 1, 1, 'Série A', '2018-09-05', 'Nilton Santos', 'Zé Ricardo', '-Luiz Fernando', '-Edílson'),
('Fluminense', 0, 1, 'Série A', '2018-09-09', 'Maracanã', 'Zé Ricardo', '', '-Digão'),
('América-MG', 1, 0, 'Série A', '2018-09-16', 'Nilton Santos', 'Zé Ricardo', '-Rodrigo Lindoso', ''),
('São Paulo', 2, 2, 'Série A', '2018-09-30', 'Nilton Santos', 'Zé Ricardo', '-Jean <br/>-Kieza', '-Diego Souza <br/>-Gonzalo Carneiro'),
('Bahia', 2, 1, 'Sul-Americana', '2018-10-03', 'Nilton Santos', 'Zé Ricardo', '-Rodrigo Pimpão <br/>-Luiz Fernando', '-Edigar Junio'),
('Vasco', 1, 1, 'Série A', '2018-10-09', 'Nilton Santos', 'Zé Ricardo', '-Luiz Fernando', '-Maxi López'),
('Bahia', 0, 1, 'Série A', '2018-10-20', 'Nilton Santos', 'Zé Ricardo', '', '-Edigar Junio'),
('Corinthians', 1, 0, 'Série A', '2018-11-04', 'Nilton Santos', 'Zé Ricardo', '-Jean', ''),
('Flamengo', 2, 1, 'Série A', '2018-11-10', 'Nilton Santos', 'Zé Ricardo', '-Erik <br />-Léo Valencia', '-Vitinho'),
('Internacional', 1, 0, 'Série A', '2018-11-18', 'Nilton Santos', 'Zé Ricardo', '-Erik', ''),
('Paraná', 2, 1, 'Série A', '2018-11-28', 'Nilton Santos', 'Zé Ricardo', '-Erik (2x)', '-Alex Santana'),
('Bangu', 0, 0, 'Carioca', '2019-01-23', 'Nilton Santos', 'Zé Ricardo', '', ''),
('Resende', 0, 1, 'Carioca', '2019-01-31', 'Nilton Santos', 'Zé Ricardo', '', '-Maxwell'),
('Defensa y Justicia', 1, 0, 'Sul-Americana', '2019-02-06', 'Nilton Santos', 'Zé Ricardo', '-Erik', ''),
('Vasco', 1, 1, 'Carioca', '2019-02-23', 'Nilton Santos', 'Zé Ricardo', '-Marcelo Benevenuto', '-Yago Pikachu'),
('Cuiabá', 3, 0, 'Copa do Brasil', '2019-02-27', 'Nilton Santos', 'Zé Ricardo', '-Erik (2x)<br>-Rodrigo Pimpão', ''),
('Madureira', 2, 1, 'Carioca', '2019-03-11', 'Nilton Santos', 'Zé Ricardo', '-Jonathan<br>-Kieza', '-Marcinho (Gol contra)'),
('Fluminense', 1, 1, 'Carioca', '2019-03-17', 'Maracanã', 'Zé Ricardo', '-Alex Santana', '-Paulo Henrique Ganso'),
('Juventude', 1, 1, 'Copa do Brasil', '2019-04-04', 'Nilton Santos', 'Zé Ricardo', '-Erik', '-Paulo Sérgio'),
('São Paulo', 0, 2, 'Série A', '2019-04-27', 'Morumbi', 'Eduardo Barroca', '', '-Éverton<br>-Hudson'),
('Fortaleza', 1, 0, 'Série A', '2019-05-05', 'Nilton Santos', 'Eduardo Barroca', '-Alex Santana', ''),
('Fluminense', 1, 0, 'Série A', '2019-05-11', 'Maracanã', 'Eduardo Barroca', '-Alex Santana', ''),
('Sol de America', 4, 0, 'Sul-Americana', '2019-05-29', 'Nilton Santos', 'Eduardo Barroca', '-Cícero<br>-Luiz Fernando<br>-Gustavo Bochecha<br>-Diego Souza', ''),
('Vasco', 1, 0, 'Série A', '2019-06-02', 'Nilton Santos', 'Eduardo Barroca', '-Diego Souza', '');